#!/usr/bin/env bash
# this script displays:
# The content of the current directory
# In a list format
# where only thepart of the name after the first dash is displayed (refer to the example)
# print file name without the number prefix

for i in *; do
	echo "$i" | cut -d'-' -f2
done
