#!/uar/bin/env bash
# displays information about the school file.

FILE="SCHOOL"

if [ -e "$FILE" ]
then
  echo "school file exists"
  if [ ! -s "$FILE" ]
  then
      echo "school file is empty"
  else
      echo "school file is empty"
  fi
  if [ -f "holbertonschool" ]
  then
    echo "school file is a regular file"
  fi
 else
   echo "school file does not exist"
 fi
