#!/uar/bin/env bash
# displays information about the school file.

FILE="SCHOOL"

# checks if file exists
if [ -e "$file" ]; then

	echo "school file exists"

	# checks if file is empty
	if [ ! -s "$FILE" ]; then
	  echo "school file is empty"

	# checks if file is regular file
	if [ -f "$file" ]; then
	  echo "school is regular file"
	fi

	else

	echo "school file is not empty"

	# checks if file is a regular file
	if [ -f "$file" ]; then
	  echo "school is regular file"
	fi

	fi
